version: '3.8'

services:
  broker_mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf


  master:
    image: 172.18.48.1:5000/tp4-master
    depends_on:
      - broker_mqtt
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure


  slave:
    image: 172.18.48.1:5000/tp5-slave-py
    depends_on:
      - master
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure


