version: '3.0'

services:
  broker_mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf


  master:
    build: 
      context: ./masterNodeJs
      dockerfile: Dockerfile
    depends_on:
      - broker_mqtt
  slave-js:
    build: 
      context: ./slavesNodeJs
      dockerfile: Dockerfile
    depends_on:
      - master